services:
  db:
    image: postgres:15 # pick your major version
    container_name: expensetracker-db
    restart: always
    ports:
      - "5432:5432" # host:container
    environment:
      POSTGRES_USER: hetk # match your DB user
      POSTGRES_PASSWORD: yourStrongPassword
      POSTGRES_DB: expensetracker
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
